# comentarios se for rodar sem compose
server:
  port: 8080
jwt:
  secretKey: jxgEQeXHuPq8VdbyYFNkANdudQ53YUn4
google:
  clientId: 336886880384-33mjig685qfsgvaivcbqkro60n6749k6.apps.googleusercontent.com
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/projeto
    username: root
    password: password
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  rabbitmq:
    host: localhost #localhost
    port: 5672
    username: guest #guest
    password: guest #guest
