server:
  port: 8088

spring:
  rabbitmq:
    host: localhost
    port: 60000
    username: rabbitmq
    password: rabbitmq
  mail:
    host: smtp.gmail.com
    port: 587
    username: projetointegracao45607@gmail.com # emailfrom, usado para
    password: fcwwinqfrodlhhaq # password app key email
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
